# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'NSGames' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NSGames
   pod 'SnapKit', '~> 5.0.0'

end

